"""sphinx_bootcampstrap.roles.constants"""

COLOR_ROLES = {
    "blue": ["text-blue"],
    "blue-light": ["text-blue-light"],
    "blue-dark": ["text-blue-dark"],
    "indigo": ["text-indigo"],
    "indigo-light": ["text-indigo-light"],
    "indigo-dark": ["text-indigo-dark"],
    "purple": ["text-purple"],
    "purple-light": ["text-purple-light"],
    "purple-dark": ["text-purple-dark"],
    "pink": ["text-pink"],
    "pink-light": ["text-pink-light"],
    "pink-dark": ["text-pink-dark"],
    "red": ["text-red"],
    "red-light": ["text-red-light"],
    "red-dark": ["text-red-dark"],
    "orange": ["text-orange"],
    "orange-light": ["text-orange-light"],
    "orange-dark": ["text-orange-dark"],
    "yellow": ["text-yellow"],
    "yellow-light": ["text-yellow-light"],
    "yellow-dark": ["text-yellow-dark"],
    "green": ["text-green"],
    "green-light": ["text-green-light"],
    "green-dark": ["text-green-dark"],
    "teal": ["text-teal"],
    "teal-light": ["text-teal-light"],
    "teal-dark": ["text-teal-dark"],
    "cyan": ["text-cyan"],
    "cyan-light": ["text-cyan-light"],
    "cyan-dark": ["text-cyan-dark"],
    "body": ["text-body"],
    "black": ["text-black"],
    "black50": ["text-black-50"],
    "white": ["text-white"],
    "white50": ["text-white-50"],
    "secondary": ["text-body-secondary"],
    "tertiary": ["text-body-tertiary"],
}
